In [1]:
import numpy as np

In [2]:
np.arange(1,100,33)

array([ 1, 34, 67])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.linspace(0,10, 3)

array([ 0.,  5., 10.])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(1)

array([0.92128385])

In [14]:
np.random.rand(2,5)

array([[0.47227402, 0.67364908, 0.05404624, 0.97286906, 0.80648836],
       [0.76876315, 0.3933719 , 0.98961608, 0.74177063, 0.71555012]])

In [17]:
np.random.randint(0,1001, (5, 2))

array([[ 39, 559],
       [  5, 759],
       [666, 781],
       [ 94, 858],
       [981, 915]])

In [18]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [20]:
arr = np.arange(0,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
randar = np.random.randint(0, 101, 10)
randar.max()
randar.argmax()

1

# Indexing

In [27]:
arr = np.arange(0,11)
arr[:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [28]:
arr = np.arange(0,11)
arr_slice = arr[0:5]
arr_slice

array([0, 1, 2, 3, 4])

In [29]:
arr_slice[:]=99
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [30]:
arr_copy = arr[:5].copy
arr_copy=100
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [33]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [36]:
arr= np.arange(0,11)
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [37]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

# Operations

In [38]:
arr = np.arange(0,10)
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [40]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [41]:
arr.var()

8.25

In [44]:
arr2 = [0,0,2,2,4,4,6,6,8,8]
(arr==arr2).sum()/len(arr2)

0.5

In [45]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr2d.sum(axis=0) #cols

array([50, 55, 60, 65, 70])